### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Luligu**
Added the installation commands for Windows and corrected a small error.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hey. I would not do it that way. On windows I think knit should be said to use a very current nodejs 18 version which includes at least npm 10.2.2+ ... this alone should solve all issues. Just installing thing nodegyp is not reliably working from my experience. Can you please check this if this solves the issues for you? Then we could add this.

**Comment by Luligu** [comment]
I already tried this is the log:
PS C:\Users\lligu\OneDrive\GitHub\matter.js> node -v
v20.10.0
PS C:\Users\lligu\OneDrive\GitHub\matter.js> npm -v
10.2.5
PS C:\Users\lligu\OneDrive\GitHub\matter.js> npm install @abandonware/noble
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\@abandonware\noble
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.1
npm ERR! gyp info using node@20.10.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.7.34221.43) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\@abandonware\\noble\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\lligu\\AppData\\Local\\node-gyp\\Cache\\20.10.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\lligu\\AppData\\Local\\node-gyp\\Cache\\20.10.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\lligu\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\20.10.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\@abandonware\\noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\@abandonware\\noble\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22631
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lligu\\OneDrive\\GitHub\\matter.js\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\lligu\OneDrive\GitHub\matter.js\node_modules\@abandonware\noble
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v9.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\lligu\AppData\Local\npm-cache\_logs\2023-12-16T12_02_24_889Z-debug-0.log
PS C:\Users\lligu\OneDrive\GitHub\matter.js>

**Comment by Apollon77** [comment]
The reason is that you have python 3.12 with a node-gyp not being 10 ... question is now why ... normally npm 10.2.3+ brings the correct node-gyp version 10 with it ... but your syystems uses node-gyp 9.4.1 which is incompatible with python 3.12 

And in fact this is the magic. 

Installing noble and bleno manually into the root of matter.js can lead to interesting other issues, so Iwould like to prevent having this as "best practice", but more tell the requirements. like

On windows make sure that ......

**Comment by Luligu** [comment]
It's correct the only requirements is to have node-gyp version 10 installed before you run npm install.

**Review by Apollon77 — APPROVED** [review]

**Pull request merged**
