### PR TITLE
Certification readiness overview

### PR DESCRIPTION
**Pull request by Apollon77**

### CODE REVIEW

**Comment by lauckhart** [comment]
Good information to track, what do you think about using the wiki for stuff like this?  On one hand it'd be nice to have updates tied to source...  On the other hand we'd have to commit to keeping it updated or it'd get bit rot.  So more casual maintenance via wiki might make sense.

Could of course check in now and revisit once we see how we do.

**Comment by lauckhart** [comment]
Another option could be to open a few topic issues with task lists.

**Comment by Apollon77** [comment]
Sure, this was just to have one place as overview. Then I would say two options

1.) We create a new discussion type (like the feature requests now) like "certification relevant todos"
2.) We use the project in github we have and create all these as entries there and label them with "cert" relevant

I did not really found a good way to make todos and status transparent (we also have the TODO.md basically) ... in fact we right now have 2 devs actively working ... you (@lauckhart) and me :-) Me on the core side, and you on generation right now ... so it is more about how we organize work here... (and for future ith more devs)

**Comment by Apollon77** [comment]
Converted to Project entries

**Pull request closed without merging**
